### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by dan-geronimo** [borodulin/yii2-select2#8]
One of your requirements in composer it can't be found
"bower-asset/select2": "~4.0.0",

( The requested package bower-asset/select2 could not be found in any version, there may be a typo in the package name. )

**Comment by borodulin** [comment]
Did you have installed any bower-\* package before?
This could be due to the absence of fxp/composer-asset-plugin. 
http://www.yiiframework.com/doc-2.0/guide-start-installation.html,
https://github.com/francoispluchino/composer-asset-plugin/#why-this-plugin
